using Mos6502Disassembler;
using NUnit.Framework;

namespace Mos6502.Test;

public class DisassemblerTests
{
    [TestCase(new byte[] { 0x00 }, MosOpcode.BRK, MosAddressingMode.Implied, 0x0, "BRK")]
    [TestCase(new byte[] { 0x01, 0x0F }, MosOpcode.ORA, MosAddressingMode.IndirectX, 0x0F, "ORA ($0F, X)")]
    [TestCase(new byte[] { 0x02 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x03 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x04 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x05, 0x11 }, MosOpcode.ORA, MosAddressingMode.ZeroPage, 0x11, "ORA $11")]
    [TestCase(new byte[] { 0x06, 0x11 }, MosOpcode.ASL, MosAddressingMode.ZeroPage, 0x11, "ASL $11")]
    [TestCase(new byte[] { 0x07 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x08 }, MosOpcode.PHP, MosAddressingMode.Implied, 0x0, "PHP")]
    [TestCase(new byte[] { 0x09, 0x11 }, MosOpcode.ORA, MosAddressingMode.Immediate, 0x11, "ORA #$11")]
    [TestCase(new byte[] { 0x0a }, MosOpcode.ASL, MosAddressingMode.Accumulator, 0x0, "ASL")]
    [TestCase(new byte[] { 0x0b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x0c }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x0d, 0x10, 0x2C }, MosOpcode.ORA, MosAddressingMode.Absolute, 0x2C10, "ORA $2C10")]
    [TestCase(new byte[] { 0x0e, 0x10, 0x2C }, MosOpcode.ASL, MosAddressingMode.Absolute, 0x2C10, "ASL $2C10")]
    [TestCase(new byte[] { 0x0f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x10, 0x11 }, MosOpcode.BPL, MosAddressingMode.Relative, 0x11, "BPL $11")]
    [TestCase(new byte[] { 0x11, 0x0F }, MosOpcode.ORA, MosAddressingMode.IndirectY, 0x0F, "ORA ($0F), Y")]
    [TestCase(new byte[] { 0x12 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x13 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x14 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x15, 0x0F }, MosOpcode.ORA, MosAddressingMode.ZeroPageX, 0x0F, "ORA $0F, X")]
    [TestCase(new byte[] { 0x16, 0x0F }, MosOpcode.ASL, MosAddressingMode.ZeroPageX, 0x0F, "ASL $0F, X")]
    [TestCase(new byte[] { 0x17 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x18 }, MosOpcode.CLC, MosAddressingMode.Implied, 0x0, "CLC")]
    [TestCase(new byte[] { 0x19, 0x10, 0x2C }, MosOpcode.ORA, MosAddressingMode.AbsoluteY, 0x2C10, "ORA $2C10, Y")]
    [TestCase(new byte[] { 0x1a }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x1b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x1c }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x1d, 0x10, 0x2C }, MosOpcode.ORA, MosAddressingMode.AbsoluteX, 0x2C10, "ORA $2C10, X")]
    [TestCase(new byte[] { 0x1e, 0x10, 0x2C }, MosOpcode.ASL, MosAddressingMode.AbsoluteX, 0x2C10, "ASL $2C10, X")]
    [TestCase(new byte[] { 0x1f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x20, 0x10, 0x2C }, MosOpcode.JSR, MosAddressingMode.Indirect, 0x2C10, "JSR ($2C10)")]
    [TestCase(new byte[] { 0x21, 0x0F }, MosOpcode.AND, MosAddressingMode.IndirectX, 0x0F, "AND ($0F, X)")]
    [TestCase(new byte[] { 0x22 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x23 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x24, 0x11 }, MosOpcode.BIT, MosAddressingMode.ZeroPage, 0x11, "BIT $11")]
    [TestCase(new byte[] { 0x25, 0x11 }, MosOpcode.AND, MosAddressingMode.ZeroPage, 0x11, "AND $11")]
    [TestCase(new byte[] { 0x26, 0x11 }, MosOpcode.ROL, MosAddressingMode.ZeroPage, 0x11, "ROL $11")]
    [TestCase(new byte[] { 0x27 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x28 }, MosOpcode.PLP, MosAddressingMode.Implied, 0x0, "PLP")]
    [TestCase(new byte[] { 0x29, 0x11 }, MosOpcode.AND, MosAddressingMode.Immediate, 0x11, "AND #$11")]
    [TestCase(new byte[] { 0x2a }, MosOpcode.ROL, MosAddressingMode.Accumulator, 0x0, "ROL")]
    [TestCase(new byte[] { 0x2b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x2c, 0x10, 0x2C }, MosOpcode.BIT, MosAddressingMode.Absolute, 0x2C10, "BIT $2C10")]
    [TestCase(new byte[] { 0x2d, 0x10, 0x2C }, MosOpcode.AND, MosAddressingMode.Absolute, 0x2C10, "AND $2C10")]
    [TestCase(new byte[] { 0x2e, 0x10, 0x2C }, MosOpcode.ROL, MosAddressingMode.Absolute, 0x2C10, "ROL $2C10")]
    [TestCase(new byte[] { 0x2f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x30, 0x11 }, MosOpcode.BMI, MosAddressingMode.Relative, 0x11, "BMI $11")]
    [TestCase(new byte[] { 0x31, 0x0F }, MosOpcode.AND, MosAddressingMode.IndirectY, 0x0F, "AND ($0F), Y")]
    [TestCase(new byte[] { 0x32 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x33 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x34 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x35, 0x0F }, MosOpcode.AND, MosAddressingMode.ZeroPageX, 0x0F, "AND $0F, X")]
    [TestCase(new byte[] { 0x36, 0x0F }, MosOpcode.ROL, MosAddressingMode.ZeroPageX, 0x0F, "ROL $0F, X")]
    [TestCase(new byte[] { 0x37 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x38 }, MosOpcode.SEC, MosAddressingMode.Implied, 0x0, "SEC")]
    [TestCase(new byte[] { 0x39, 0x10, 0x2C }, MosOpcode.AND, MosAddressingMode.AbsoluteY, 0x2C10, "AND $2C10, Y")]
    [TestCase(new byte[] { 0x3a }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x3b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x3c }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x3d, 0x10, 0x2C }, MosOpcode.AND, MosAddressingMode.AbsoluteX, 0x2C10, "AND $2C10, X")]
    [TestCase(new byte[] { 0x3e, 0x10, 0x2C }, MosOpcode.ROL, MosAddressingMode.AbsoluteX, 0x2C10, "ROL $2C10, X")]
    [TestCase(new byte[] { 0x3f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x40 }, MosOpcode.RTI, MosAddressingMode.Implied, 0x0, "RTI")]
    [TestCase(new byte[] { 0x41, 0x0F }, MosOpcode.EOR, MosAddressingMode.IndirectX, 0x0F, "EOR ($0F, X)")]
    [TestCase(new byte[] { 0x42 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x43 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x44 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x45, 0x11 }, MosOpcode.EOR, MosAddressingMode.ZeroPage, 0x11, "EOR $11")]
    [TestCase(new byte[] { 0x46, 0x11 }, MosOpcode.LSR, MosAddressingMode.ZeroPage, 0x11, "LSR $11")]
    [TestCase(new byte[] { 0x47 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x48 }, MosOpcode.PHA, MosAddressingMode.Implied, 0x0, "PHA")]
    [TestCase(new byte[] { 0x49, 0x11 }, MosOpcode.EOR, MosAddressingMode.Immediate, 0x11, "EOR #$11")]
    [TestCase(new byte[] { 0x4a }, MosOpcode.LSR, MosAddressingMode.Accumulator, 0x0, "LSR")]
    [TestCase(new byte[] { 0x4b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x4c, 0x10, 0x2C }, MosOpcode.JMP, MosAddressingMode.Absolute, 0x2C10, "JMP $2C10")]
    [TestCase(new byte[] { 0x4d, 0x10, 0x2C }, MosOpcode.EOR, MosAddressingMode.Absolute, 0x2C10, "EOR $2C10")]
    [TestCase(new byte[] { 0x4e, 0x10, 0x2C }, MosOpcode.LSR, MosAddressingMode.Absolute, 0x2C10, "LSR $2C10")]
    [TestCase(new byte[] { 0x4f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x50, 0x11 }, MosOpcode.BVC, MosAddressingMode.Relative, 0x11, "BVC $11")]
    [TestCase(new byte[] { 0x51, 0x0F }, MosOpcode.EOR, MosAddressingMode.IndirectY, 0x0F, "EOR ($0F), Y")]
    [TestCase(new byte[] { 0x52 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x53 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x54 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x55, 0x0F }, MosOpcode.EOR, MosAddressingMode.ZeroPageX, 0x0F, "EOR $0F, X")]
    [TestCase(new byte[] { 0x56, 0x0F }, MosOpcode.LSR, MosAddressingMode.ZeroPageX, 0x0F, "LSR $0F, X")]
    [TestCase(new byte[] { 0x57 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x58 }, MosOpcode.CLI, MosAddressingMode.Implied, 0x0, "CLI")]
    [TestCase(new byte[] { 0x59, 0x10, 0x2C }, MosOpcode.EOR, MosAddressingMode.AbsoluteY, 0x2C10, "EOR $2C10, Y")]
    [TestCase(new byte[] { 0x5a }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x5b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x5c }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x5d, 0x10, 0x2C }, MosOpcode.EOR, MosAddressingMode.AbsoluteX, 0x2C10, "EOR $2C10, X")]
    [TestCase(new byte[] { 0x5e, 0x10, 0x2C }, MosOpcode.LSR, MosAddressingMode.AbsoluteX, 0x2C10, "LSR $2C10, X")]
    [TestCase(new byte[] { 0x5f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x60 }, MosOpcode.RTS, MosAddressingMode.Implied, 0x0, "RTS")]
    [TestCase(new byte[] { 0x61, 0x0F }, MosOpcode.ADC, MosAddressingMode.IndirectX, 0x0F, "ADC ($0F, X)")]
    [TestCase(new byte[] { 0x62 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x63 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x64 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x65, 0x11 }, MosOpcode.ADC, MosAddressingMode.ZeroPage, 0x11, "ADC $11")]
    [TestCase(new byte[] { 0x66, 0x11 }, MosOpcode.ROR, MosAddressingMode.ZeroPage, 0x11, "ROR $11")]
    [TestCase(new byte[] { 0x67 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x68 }, MosOpcode.PLA, MosAddressingMode.Implied, 0x0, "PLA")]
    [TestCase(new byte[] { 0x69, 0x11 }, MosOpcode.ADC, MosAddressingMode.Immediate, 0x11, "ADC #$11")]
    [TestCase(new byte[] { 0x6a }, MosOpcode.ROR, MosAddressingMode.Accumulator, 0x0, "ROR")]
    [TestCase(new byte[] { 0x6b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x6c, 0x10, 0x20 }, MosOpcode.JMP, MosAddressingMode.Indirect, 0x2010, "JMP ($2010)")]
    [TestCase(new byte[] { 0x6d, 0x10, 0x2C }, MosOpcode.ADC, MosAddressingMode.Absolute, 0x2C10, "ADC $2C10")]
    [TestCase(new byte[] { 0x6e, 0x10, 0x2C }, MosOpcode.ROR, MosAddressingMode.Absolute, 0x2C10, "ROR $2C10")]
    [TestCase(new byte[] { 0x6f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x70, 0x11 }, MosOpcode.BVS, MosAddressingMode.Relative, 0x11, "BVS $11")]
    [TestCase(new byte[] { 0x71, 0x0F }, MosOpcode.ADC, MosAddressingMode.IndirectY, 0x0F, "ADC ($0F), Y")]
    [TestCase(new byte[] { 0x72 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x73 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x74 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x75, 0x0F }, MosOpcode.ADC, MosAddressingMode.ZeroPageX, 0x0F, "ADC $0F, X")]
    [TestCase(new byte[] { 0x76, 0x0F }, MosOpcode.ROR, MosAddressingMode.ZeroPageX, 0x0F, "ROR $0F, X")]
    [TestCase(new byte[] { 0x77 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x78 }, MosOpcode.SEI, MosAddressingMode.Implied, 0x0, "SEI")]
    [TestCase(new byte[] { 0x79, 0x10, 0x2C }, MosOpcode.ADC, MosAddressingMode.AbsoluteY, 0x2C10, "ADC $2C10, Y")]
    [TestCase(new byte[] { 0x7a }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x7b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x7c }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x7d, 0x10, 0x2C }, MosOpcode.ADC, MosAddressingMode.AbsoluteX, 0x2C10, "ADC $2C10, X")]
    [TestCase(new byte[] { 0x7e, 0x10, 0x2C }, MosOpcode.ROR, MosAddressingMode.AbsoluteX, 0x2C10, "ROR $2C10, X")]
    [TestCase(new byte[] { 0x7f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x80 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x81, 0x0F }, MosOpcode.STA, MosAddressingMode.IndirectX, 0x0F, "STA ($0F, X)")]
    [TestCase(new byte[] { 0x82 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x83 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x84, 0x11 }, MosOpcode.STY, MosAddressingMode.ZeroPage, 0x11, "STY $11")]
    [TestCase(new byte[] { 0x85, 0x11 }, MosOpcode.STA, MosAddressingMode.ZeroPage, 0x11, "STA $11")]
    [TestCase(new byte[] { 0x86, 0x11 }, MosOpcode.STX, MosAddressingMode.ZeroPage, 0x11, "STX $11")]
    [TestCase(new byte[] { 0x87 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x88 }, MosOpcode.DEY, MosAddressingMode.Implied, 0x0, "DEY")]
    [TestCase(new byte[] { 0x89 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x8a }, MosOpcode.TXA, MosAddressingMode.Implied, 0x0, "TXA")]
    [TestCase(new byte[] { 0x8b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x8c, 0x10, 0x2C }, MosOpcode.STY, MosAddressingMode.Absolute, 0x2C10, "STY $2C10")]
    [TestCase(new byte[] { 0x8d, 0x10, 0x2C }, MosOpcode.STA, MosAddressingMode.Absolute, 0x2C10, "STA $2C10")]
    [TestCase(new byte[] { 0x8e, 0x10, 0x2C }, MosOpcode.STX, MosAddressingMode.Absolute, 0x2C10, "STX $2C10")]
    [TestCase(new byte[] { 0x8f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x90, 0x11 }, MosOpcode.BCC, MosAddressingMode.Relative, 0x11, "BCC $11")]
    [TestCase(new byte[] { 0x91, 0x0F }, MosOpcode.STA, MosAddressingMode.IndirectY, 0x0F, "STA ($0F), Y")]
    [TestCase(new byte[] { 0x92 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0x93 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x94, 0x0F }, MosOpcode.STY, MosAddressingMode.ZeroPageX, 0x0F, "STY $0F, X")]
    [TestCase(new byte[] { 0x95, 0x0F }, MosOpcode.STA, MosAddressingMode.ZeroPageX, 0x0F, "STA $0F, X")]
    [TestCase(new byte[] { 0x96, 0x0F }, MosOpcode.STX, MosAddressingMode.ZeroPageY, 0x0F, "STX $0F, Y")]
    [TestCase(new byte[] { 0x97 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x98 }, MosOpcode.TYA, MosAddressingMode.Implied, 0x0, "TYA")]
    [TestCase(new byte[] { 0x99, 0x10, 0x2C }, MosOpcode.STA, MosAddressingMode.AbsoluteY, 0x2C10, "STA $2C10, Y")]
    [TestCase(new byte[] { 0x9a }, MosOpcode.TXS, MosAddressingMode.Implied, 0x0, "TXS")]
    [TestCase(new byte[] { 0x9b }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x9c }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x9d, 0x10, 0x2C }, MosOpcode.STA, MosAddressingMode.AbsoluteX, 0x2C10, "STA $2C10, X")]
    [TestCase(new byte[] { 0x9e }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0x9f }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xa0, 0x11 }, MosOpcode.LDY, MosAddressingMode.Immediate, 0x11, "LDY #$11")]
    [TestCase(new byte[] { 0xa1, 0x0F }, MosOpcode.LDA, MosAddressingMode.IndirectX, 0x0F, "LDA ($0F, X)")]
    [TestCase(new byte[] { 0xa2, 0x11 }, MosOpcode.LDX, MosAddressingMode.Immediate, 0x11, "LDX #$11")]
    [TestCase(new byte[] { 0xa3 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xa4, 0x11 }, MosOpcode.LDY, MosAddressingMode.ZeroPage, 0x11, "LDY $11")]
    [TestCase(new byte[] { 0xa5, 0x11 }, MosOpcode.LDA, MosAddressingMode.ZeroPage, 0x11, "LDA $11")]
    [TestCase(new byte[] { 0xa6, 0x11 }, MosOpcode.LDX, MosAddressingMode.ZeroPage, 0x11, "LDX $11")]
    [TestCase(new byte[] { 0xa7 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xa8 }, MosOpcode.TAY, MosAddressingMode.Implied, 0x0, "TAY")]
    [TestCase(new byte[] { 0xa9, 0x11 }, MosOpcode.LDA, MosAddressingMode.Immediate, 0x11, "LDA #$11")]
    [TestCase(new byte[] { 0xaa }, MosOpcode.TAX, MosAddressingMode.Implied, 0x0, "TAX")]
    [TestCase(new byte[] { 0xab }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xac, 0x10, 0x2C }, MosOpcode.LDY, MosAddressingMode.Absolute, 0x2C10, "LDY $2C10")]
    [TestCase(new byte[] { 0xad, 0x10, 0x2C }, MosOpcode.LDA, MosAddressingMode.Absolute, 0x2C10, "LDA $2C10")]
    [TestCase(new byte[] { 0xae, 0x10, 0x2C }, MosOpcode.LDX, MosAddressingMode.Absolute, 0x2C10, "LDX $2C10")]
    [TestCase(new byte[] { 0xaf }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xb0, 0x11 }, MosOpcode.BCS, MosAddressingMode.Relative, 0x11, "BCS $11")]
    [TestCase(new byte[] { 0xb1, 0x0F }, MosOpcode.LDA, MosAddressingMode.IndirectY, 0x0F, "LDA ($0F), Y")]
    [TestCase(new byte[] { 0xb2 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0xb3 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xb4, 0x0F }, MosOpcode.LDY, MosAddressingMode.ZeroPageX, 0x0F, "LDY $0F, X")]
    [TestCase(new byte[] { 0xb5, 0x0F }, MosOpcode.LDA, MosAddressingMode.ZeroPageX, 0x0F, "LDA $0F, X")]
    [TestCase(new byte[] { 0xb6, 0x0F }, MosOpcode.LDX, MosAddressingMode.ZeroPageY, 0x0F, "LDX $0F, Y")]
    [TestCase(new byte[] { 0xb7 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xb8 }, MosOpcode.CLV, MosAddressingMode.Implied, 0x0, "CLV")]
    [TestCase(new byte[] { 0xb9, 0x10, 0x2C }, MosOpcode.LDA, MosAddressingMode.AbsoluteY, 0x2C10, "LDA $2C10, Y")]
    [TestCase(new byte[] { 0xba }, MosOpcode.TSX, MosAddressingMode.Implied, 0x0, "TSX")]
    [TestCase(new byte[] { 0xbb }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xbc, 0x10, 0x2C }, MosOpcode.LDY, MosAddressingMode.AbsoluteX, 0x2C10, "LDY $2C10, X")]
    [TestCase(new byte[] { 0xbd, 0x10, 0x2C }, MosOpcode.LDA, MosAddressingMode.AbsoluteX, 0x2C10, "LDA $2C10, X")]
    [TestCase(new byte[] { 0xbe, 0x10, 0x2C }, MosOpcode.LDX, MosAddressingMode.AbsoluteY, 0x2C10, "LDX $2C10, Y")]
    [TestCase(new byte[] { 0xbf }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xc0, 0x11 }, MosOpcode.CPY, MosAddressingMode.Immediate, 0x11, "CPY #$11")]
    [TestCase(new byte[] { 0xc1, 0x0F }, MosOpcode.CMP, MosAddressingMode.IndirectX, 0x0F, "CMP ($0F, X)")]
    [TestCase(new byte[] { 0xc2 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xc3 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xc4, 0x11 }, MosOpcode.CPY, MosAddressingMode.ZeroPage, 0x11, "CPY $11")]
    [TestCase(new byte[] { 0xc5, 0x11 }, MosOpcode.CMP, MosAddressingMode.ZeroPage, 0x11, "CMP $11")]
    [TestCase(new byte[] { 0xc6, 0x11 }, MosOpcode.DEC, MosAddressingMode.ZeroPage, 0x11, "DEC $11")]
    [TestCase(new byte[] { 0xc7 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xc8 }, MosOpcode.INY, MosAddressingMode.Implied, 0x0, "INY")]
    [TestCase(new byte[] { 0xc9, 0x11 }, MosOpcode.CMP, MosAddressingMode.Immediate, 0x11, "CMP #$11")]
    [TestCase(new byte[] { 0xca }, MosOpcode.DEX, MosAddressingMode.Implied, 0x0, "DEX")]
    [TestCase(new byte[] { 0xcb }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xcc, 0x10, 0x2C }, MosOpcode.CPY, MosAddressingMode.Absolute, 0x2C10, "CPY $2C10")]
    [TestCase(new byte[] { 0xcd, 0x10, 0x2C }, MosOpcode.CMP, MosAddressingMode.Absolute, 0x2C10, "CMP $2C10")]
    [TestCase(new byte[] { 0xce, 0x10, 0x2C }, MosOpcode.DEC, MosAddressingMode.Absolute, 0x2C10, "DEC $2C10")]
    [TestCase(new byte[] { 0xcf }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xd0, 0x11 }, MosOpcode.BNE, MosAddressingMode.Relative, 0x11, "BNE $11")]
    [TestCase(new byte[] { 0xd1, 0x0F }, MosOpcode.CMP, MosAddressingMode.IndirectY, 0x0F, "CMP ($0F), Y")]
    [TestCase(new byte[] { 0xd2 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0xd3 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xd4 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xd5, 0x0F }, MosOpcode.CMP, MosAddressingMode.ZeroPageX, 0x0F, "CMP $0F, X")]
    [TestCase(new byte[] { 0xd6, 0x0F }, MosOpcode.DEC, MosAddressingMode.ZeroPageX, 0x0F, "DEC $0F, X")]
    [TestCase(new byte[] { 0xd7 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xd8 }, MosOpcode.CLD, MosAddressingMode.Implied, 0x0, "CLD")]
    [TestCase(new byte[] { 0xd9, 0x10, 0x2C }, MosOpcode.CMP, MosAddressingMode.AbsoluteY, 0x2C10, "CMP $2C10, Y")]
    [TestCase(new byte[] { 0xda }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xdb }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xdc }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xdd, 0x10, 0x2C }, MosOpcode.CMP, MosAddressingMode.AbsoluteX, 0x2C10, "CMP $2C10, X")]
    [TestCase(new byte[] { 0xde, 0x10, 0x2C }, MosOpcode.DEC, MosAddressingMode.AbsoluteX, 0x2C10, "DEC $2C10, X")]
    [TestCase(new byte[] { 0xdf }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xe0, 0x11 }, MosOpcode.CPX, MosAddressingMode.Immediate, 0x11, "CPX #$11")]
    [TestCase(new byte[] { 0xe1, 0x0F }, MosOpcode.SBC, MosAddressingMode.IndirectX, 0x0F, "SBC ($0F, X)")]
    [TestCase(new byte[] { 0xe2 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xe3 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xe4, 0x11 }, MosOpcode.CPX, MosAddressingMode.ZeroPage, 0x11, "CPX $11")]
    [TestCase(new byte[] { 0xe5, 0x11 }, MosOpcode.SBC, MosAddressingMode.ZeroPage, 0x11, "SBC $11")]
    [TestCase(new byte[] { 0xe6, 0x11 }, MosOpcode.INC, MosAddressingMode.ZeroPage, 0x11, "INC $11")]
    [TestCase(new byte[] { 0xe7 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xe8 }, MosOpcode.INX, MosAddressingMode.Implied, 0x0, "INX")]
    [TestCase(new byte[] { 0xe9, 0x11 }, MosOpcode.SBC, MosAddressingMode.Immediate, 0x11, "SBC #$11")]
    [TestCase(new byte[] { 0xea }, MosOpcode.NOP, MosAddressingMode.Implied, 0x0, "NOP")]
    [TestCase(new byte[] { 0xeb }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xec, 0x10, 0x2C }, MosOpcode.CPX, MosAddressingMode.Absolute, 0x2C10, "CPX $2C10")]
    [TestCase(new byte[] { 0xed, 0x10, 0x2C }, MosOpcode.SBC, MosAddressingMode.Absolute, 0x2C10, "SBC $2C10")]
    [TestCase(new byte[] { 0xee, 0x10, 0x2C }, MosOpcode.INC, MosAddressingMode.Absolute, 0x2C10, "INC $2C10")]
    [TestCase(new byte[] { 0xef }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xf0, 0x11 }, MosOpcode.BEQ, MosAddressingMode.Relative, 0x11, "BEQ $11")]
    [TestCase(new byte[] { 0xf1, 0x0F }, MosOpcode.SBC, MosAddressingMode.IndirectY, 0x0F, "SBC ($0F), Y")]
    [TestCase(new byte[] { 0xf2 }, MosOpcode.HLT, MosAddressingMode.Implied, 0x0, "HLT")]
    [TestCase(new byte[] { 0xf3 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xf4 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xf5, 0x0F }, MosOpcode.SBC, MosAddressingMode.ZeroPageX, 0x0F, "SBC $0F, X")]
    [TestCase(new byte[] { 0xf6, 0x0F }, MosOpcode.INC, MosAddressingMode.ZeroPageX, 0x0F, "INC $0F, X")]
    [TestCase(new byte[] { 0xf7 }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xf8 }, MosOpcode.SED, MosAddressingMode.Implied, 0x0, "SED")]
    [TestCase(new byte[] { 0xf9, 0x10, 0x2C }, MosOpcode.SBC, MosAddressingMode.AbsoluteY, 0x2C10, "SBC $2C10, Y")]
    [TestCase(new byte[] { 0xfa }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xfb }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xfc }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    [TestCase(new byte[] { 0xfd, 0x10, 0x2C }, MosOpcode.SBC, MosAddressingMode.AbsoluteX, 0x2C10, "SBC $2C10, X")]
    [TestCase(new byte[] { 0xfe, 0x10, 0x2C }, MosOpcode.INC, MosAddressingMode.AbsoluteX, 0x2C10, "INC $2C10, X")]
    [TestCase(new byte[] { 0xff }, MosOpcode.Illegal, MosAddressingMode.Illegal, 0x0, "")]
    public void TestDisassembler(byte[] bytes, MosOpcode opcode, MosAddressingMode addressing, int operand, string str)
    {
        try
        {
            var instr = MosDisassembler.DecodeInstruction(bytes, out var bytesRead);
            Assert.AreEqual(opcode, instr.Opcode, str);
            Assert.AreEqual(addressing, instr.AddressingMode, str);
            Assert.AreEqual(operand, instr.Operand, str);
            Assert.AreEqual(bytes.Length, bytesRead, str);
        }
        catch (IllegalInstructionException e)
        {
            if (opcode != MosOpcode.Illegal)
                Assert.Fail(e.Message);
        }
    }
}